function [ MAVdatasets] = errorPerSequenceMAV( supplementaryFolder )

MAVdatasets = { ...
	struct( ...
		'name', 'mav_MH_01_easy', ...
		'startframe', 950, ...
		'endframe', 3600 ...
	), ...
	struct( ...
		'name', 'mav_MH_02_easy', ...
		'startframe', 800, ...
		'endframe', 3000 ...
	), ...
	struct( ...
		'name', 'mav_MH_03_medium', ...
		'startframe', 410, ...
		'endframe', 2600 ...
	), ...
	struct( ...
		'name', 'mav_MH_04_difficult', ...
		'startframe', 445, ...
		'endframe', 1925 ...
	), ...
	struct( ...
		'name', 'mav_MH_05_difficult', ...
		'startframe', 460, ...
		'endframe', 2200 ...
	), ...
	struct( ...
		'name', 'mav_V1_01_easy', ...
		'startframe', 0, ...
		'endframe', 2800 ...
	), ...
	struct( ...
		'name', 'mav_V1_02_medium', ...
		'startframe', 115, ...
		'endframe', 1600 ...
	), ...
	struct( ...
		'name', 'mav_V1_03_difficult', ...
		'startframe', 250, ...
		'endframe', 2020 ...
	), ...
	struct( ...
		'name', 'mav_V2_01_easy', ...
		'startframe', 0, ...
		'endframe', 2130 ...
	), ...
	struct( ...
		'name', 'mav_V2_02_medium', ...
		'startframe', 100, ...
		'endframe', 2230 ...
	), ...
	struct( ...
		'name', 'mav_V2_03_difficult', ...
		'startframe', 115, ...
		'endframe', 1880 ...
	), ...
	struct( ...
		'name', 'mav2_MH_01_easy', ...
		'startframe', 950, ...
		'endframe', 3600 ...
	), ...
	struct( ...
		'name', 'mav2_MH_02_easy', ...
		'startframe', 800, ...
		'endframe', 3000 ...
	), ...
	struct( ...
		'name', 'mav2_MH_03_medium', ...
		'startframe', 410, ...
		'endframe', 2600 ...
	), ...
	struct( ...
		'name', 'mav2_MH_04_difficult', ...
		'startframe', 445, ...
		'endframe', 1925 ...
	), ...
	struct( ...
		'name', 'mav2_MH_05_difficult', ...
		'startframe', 460, ...
		'endframe', 2200 ...
	), ...
	struct( ...
		'name', 'mav2_V1_01_easy', ...
		'startframe', 0, ...
		'endframe', 2800 ...
	), ...
	struct( ...
		'name', 'mav2_V1_02_medium', ...
		'startframe', 115, ...
		'endframe', 1600 ...
	), ...
	struct( ...
		'name', 'mav2_V1_03_difficult', ...
		'startframe', 250, ...
		'endframe', 2020 ...
	), ...
	struct( ...
		'name', 'mav2_V2_01_easy', ...
		'startframe', 0, ...
		'endframe', 2130 ...
	), ...
	struct( ...
		'name', 'mav2_V2_02_medium', ...
		'startframe', 100, ...
		'endframe', 2230 ...
	), ...
	struct( ...
		'name', 'mav2_V2_03_difficult', ...
		'startframe', 115, ...
		'endframe', 1880 ...
	) ...
};

for d=1:size(MAVdatasets, 2)
    tms = importdata([ supplementaryFolder '/timesFiles/' MAVdatasets{d}.name '.txt']);
    num= size(tms,1);
    MAVdatasets{d}.startTime = tms(MAVdatasets{d}.startframe+1,2);
    MAVdatasets{d}.endTime = tms(MAVdatasets{d}.endframe+1,2);
    MAVdatasets{d}.seconds = MAVdatasets{d}.endTime - MAVdatasets{d}.startTime;
    MAVdatasets{d}.mocapRaw = importdata([ supplementaryFolder '/gtFiles/' MAVdatasets{d}.name '.txt']);
end



end